In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [2]:
michelin_restaurants = pd.read_csv('../data/michelin_restaurants.csv', encoding = 'latin1')

In [3]:
michelin_restaurants.head()

,Name,Address,Location,MinPrice,MaxPrice,Currency,Cuisine,Longitude,Latitude,PhoneNumber,Url,WebsiteUrl,Award,FacilitiesAndServices
0,Les Amis,"Shaw Centre, #01-16, 1 Scotts Road, 228208, Si...",Singapore,225,460,SGD,French,103.832040,1.306260,6.567332e+09,https://guide.michelin.com/en/singapore-region...,https://www.lesamis.com.sg/,3 MICHELIN Stars,"Air conditioning,American Express credit card,..."
1,Odette,"National Gallery, #01-04, 1 St. Andrew's Road ...",Singapore,298,428,SGD,French Contemporary,103.851600,1.289646,6.563850e+09,https://guide.michelin.com/en/singapore-region...,http://www.odetterestaurant.com,3 MICHELIN Stars,"Air conditioning,American Express credit card,..."
2,ZÃ©n,"41 Bukit Pasoh Road, 089855, Singapore",Singapore,580,580,SGD,European Contemporary,103.840420,1.279627,6.592366e+09,https://guide.michelin.com/en/singapore-region...,http://www.restaurantzen.com,3 MICHELIN Stars,"Air conditioning,American Express credit card,..."
3,Maaemo,"Dronning Eufemias gate 23, Oslo, 0194, Norway",Oslo,"3,500","3,500",NOK,"Modern Cuisine, Creative",10.758636,59.907529,4.722180e+09,https://guide.michelin.com/en/oslo-region/oslo...,http://www.maaemo.no,3 MICHELIN Stars,"Air conditioning,American Express credit card,..."
4,Geranium,"Per Henrik Lings AllÃ©, Parken National Stadiu...",Copenhagen,"3,200","3,200",DKK,"Creative, Contemporary",12.572529,55.704085,4.569960e+09,https://guide.michelin.com/en/capital-region/c...,https://www.geranium.dk/,3 MICHELIN Stars,"Air conditioning,American Express credit card,..."

In [4]:
michelin_restaurants.shape

(6527, 14)

In [5]:
michelin_restaurants.columns

Index(['Name', 'Address', 'Location', 'MinPrice', 'MaxPrice', 'Currency',
       'Cuisine', 'Longitude', 'Latitude', 'PhoneNumber', 'Url', 'WebsiteUrl',
       'Award', 'FacilitiesAndServices'],
      dtype='object')

In [6]:
michelin_restaurants.drop_duplicates().shape, michelin_restaurants.shape

((6527, 14), (6527, 14))

In [7]:
michelin_restaurants.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6527 entries, 0 to 6526
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Name                   6527 non-null   object
 1   Address                6527 non-null   object
 2   Location               6527 non-null   object
 3   MinPrice               6522 non-null   object
 4   MaxPrice               6522 non-null   object
 5   Currency               6522 non-null   object
 6   Cuisine                6527 non-null   object
 7   Longitude              6527 non-null   float64
 8   Latitude               6527 non-null   float64
 9   PhoneNumber            6405 non-null   float64
 10  Url                    6527 non-null   object
 11  WebsiteUrl             5399 non-null   object
 12  Award                  6527 non-null   object
 13  FacilitiesAndServices  6491 non-null   object
dtypes: float64(3), object(11)
memory usage: 6.4 MB

In [8]:
michelin_restaurants['MinPrice']=michelin_restaurants['MinPrice'].str.replace(',','')
michelin_restaurants['MaxPrice']=michelin_restaurants['MaxPrice'].str.replace(',','')

michelin_restaurants['MinPrice'] = pd.to_numeric(michelin_restaurants['MinPrice'],downcast='integer')
michelin_restaurants['MaxPrice'] = pd.to_numeric(michelin_restaurants['MaxPrice'],downcast='integer')
michelin_restaurants.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6527 entries, 0 to 6526
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Name                   6527 non-null   object
 1   Address                6527 non-null   object
 2   Location               6527 non-null   object
 3   MinPrice               6522 non-null   float64
 4   MaxPrice               6522 non-null   float64
 5   Currency               6522 non-null   object
 6   Cuisine                6527 non-null   object
 7   Longitude              6527 non-null   float64
 8   Latitude               6527 non-null   float64
 9   PhoneNumber            6405 non-null   float64
 10  Url                    6527 non-null   object
 11  WebsiteUrl             5399 non-null   object
 12  Award                  6527 non-null   object
 13  FacilitiesAndServices  6491 non-null   object
dtypes: float64(5), object(9)
memory usage: 5.7 MB

In [10]:
michelin_restaurants['Address'] = michelin_restaurants['Address'].str.rsplit(',',1).str[1]

In [17]:
michelin_restaurants = michelin_restaurants.rename(columns={'Address': 'Country'})
michelin_restaurants.head()

,Name,Country,Location,MinPrice,MaxPrice,Currency,Cuisine,Longitude,Latitude,PhoneNumber,Url,WebsiteUrl,Award,FacilitiesAndServices
0,Les Amis,Singapore,Singapore,225.0,460.0,SGD,French,103.832040,1.306260,6.567332e+09,https://guide.michelin.com/en/singapore-region...,https://www.lesamis.com.sg/,3 MICHELIN Stars,"Air conditioning,American Express credit card,..."
1,Odette,Singapore,Singapore,298.0,428.0,SGD,French Contemporary,103.851600,1.289646,6.563850e+09,https://guide.michelin.com/en/singapore-region...,http://www.odetterestaurant.com,3 MICHELIN Stars,"Air conditioning,American Express credit card,..."
2,ZÃ©n,Singapore,Singapore,580.0,580.0,SGD,European Contemporary,103.840420,1.279627,6.592366e+09,https://guide.michelin.com/en/singapore-region...,http://www.restaurantzen.com,3 MICHELIN Stars,"Air conditioning,American Express credit card,..."
3,Maaemo,Norway,Oslo,3500.0,3500.0,NOK,"Modern Cuisine, Creative",10.758636,59.907529,4.722180e+09,https://guide.michelin.com/en/oslo-region/oslo...,http://www.maaemo.no,3 MICHELIN Stars,"Air conditioning,American Express credit card,..."
4,Geranium,Denmark,Copenhagen,3200.0,3200.0,DKK,"Creative, Contemporary",12.572529,55.704085,4.569960e+09,https://guide.michelin.com/en/capital-region/c...,https://www.geranium.dk/,3 MICHELIN Stars,"Air conditioning,American Express credit card,..."